# reviewdog.yml

runner:
  golint:
    cmd: golint $(go list ./... | grep -v /vendor/)
    format: golint
    level: warning
  golangci:
    cmd: golangci-lint run --out-format=line-number ./...
    errorformat:
      - '%E%f:%l:%c: %m'
      - '%E%f:%l: %m'
      - '%C%.%#'
    level: warning
