version: 2.1
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/YutaGoto/ika2cli
    steps:
      - run: echo 'export PATH=${GOPATH}/bin/:${PATH}' >> $BASH_ENV
      - checkout
      - run: go get gopkg.in/alecthomas/kingpin.v2
      - run: go get github.com/golang/lint/golint
      - run:
          name: test
          command: |
            go test -v -coverprofile c.out ./...
