version: 2.1
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: CC_TEST_REPORTER_ID
    docker:
      # specify the version
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/YutaGoto/ika2cli
    steps:
      - run: echo 'export PATH=${GOPATH}/bin/:${PATH}' >> $BASH_ENV
      - checkout
      - run: go get -v -t -d ./...
      - run: go get github.com/golang/lint/golint
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: test
          command: |
            ./cc-test-reporter before-build
            go test -v -coverprofile c.out ./...
            ./cc-test-reporter after-build --coverage-input-type simplecov --exit-code $?
